### ISSUE TITLE
ErrorProne.NET.StructAnalyzers.MakeStructReadOnlyAnalyzer' threw an exception of type 'System.MissingMethodException'

### ISSUE THREAD

**Issue by rotanov** [SergeyTeplyakov/ErrorProne.NET#222] opened 2021-03-09 20:54 UTC
Installed latest beta of both analyzer packages from nuget to my NET5.0 project. 
Apparently it doesn't work, since I don't see squiggles when I change not-read-only-struct-argument to `in`.
I also see about ~500 lines when building application, all of them are the same:
```
2>CSC : warning AD0001: Analyzer 'ErrorProne.NET.StructAnalyzers.MakeStructReadOnlyAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'Boolean ErrorProne.NET.Core.TypeExtensions.IsReadOnlyStruct(Microsoft.CodeAnalysis.INamedTypeSymbol)'.'.
```

**Comment by SergeyTeplyakov** [comment] 2021-03-09 22:30
Thanks for reporting the issue.
Looking...

**Comment by Djoums** [comment] 2021-09-03 04:54
Bump, latest stable release works but not the prereleases (same error as OP).

**Comment by rotanov** [comment] 2021-09-04 05:57
Yeah, I tried installing ErrorProne.NET nuget last week again and had no issues.

**Comment by Djoums** [comment] 2021-09-08 12:58
I can't reproduce it anymore either, not sure what to think. It worked at some point and now no error when uninstalling/reinstalling.

**Comment by rotanov** [comment] 2021-09-08 14:16
@SergeyTeplyakov Shall I close the issue?

**Comment by SergeyTeplyakov** [comment] 2021-09-08 21:39
I have a theory here: I think its impossible to use different versions 'ErrorProne.NEET.CoreAnalyzers' and 'ErrorProne.NET.StructAnalyzers', because both of them rely on 'ErroorProne.NET.Core.dl'. So if the analyzer version s are different its possible that they will rely on the different version of 'ErrorProne.NET.Core.dll', but VS will load only one of them. So one of the analyzers will work and the other will fail with 'MissingMethodException'. Then recently I updated both analyzers to reference the same 'Core.dll'.

And I have a PR to remove the dependency whatsoever to avoid this issue in the future. So I think we can close this one.

**Closed by SergeyTeplyakov** 2021-09-08 21:39 UTC
