### ISSUE TITLE
EPS02 Occurring on ReadOnlyMemory

### ISSUE THREAD

**Issue by Mike-E-wins** [SergeyTeplyakov/ErrorProne.NET#84] opened 2018-09-15 15:40 UTC
First off, THANK YOU for making these analyzers!  I have been scratching my cranium trying to figure out all the struct black magic that has been introduced, and keeping track of all the tedious rules has been quite challenging.  TBH I am surprised that ReSharper hasn't had this implemented already.

Anyways, I have some EPS02's occurring on `ReadOnlyMemory`.  The message is:

```
Non-readonly struct 'ReadOnlyMemory' used as in-parameter 'this'
```

From my understanding, `ReadOnlyMemory` is a readonly struct.  Perhaps I am misunderstanding something here.  I am little hazy on how all the pieces still fit together.  For instance, I do not see readonly here:

https://apisof.net/catalog/System.ReadOnlyMemory%3CT%3E

In my case, I am using System.Memory so perhaps that is overriding it?  Any insight/explanation would be greatly appreciated.

Thanks again for making this!

**Comment by SergeyTeplyakov** [comment] 2018-10-03 06:46
From the link you've provided, I can't see that the struct is readonly:

```csharp
namespace System
{  
  
  [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public struct ReadOnlyMemory<T>
}
```

Even though it is readonly in corefx repo: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/ReadOnlyMemory.cs#L22

But then I just created an empty Console Core app, added the most recent analyzers and add the following:

```csharp
struct LargeStruct
{
    private readonly long l1, l2, l3;
    public int Foo() => 42;
}

// No warnings
static void FooBar(in System.ReadOnlyMemory<int> mi)
{
    Console.WriteLine(mi.Pin().ToString());
}

// Warning!
static void ShouldWarn(in LargeStruct ls)
{ }
```

Can you check the latest version published here: https://www.nuget.org/packages/ErrorProne.NET.Structs/0.1.1.10

**Comment by Mike-EEE** [comment] 2018-10-03 10:43
Funny enough I have not had this problem since I reported it.  

The issue is due to reference assemblies.  In my case, the warnings were happening on a .NET Standard 2.0 library that referenced System.Memory 4.5.1.  Perhaps there's an issue where before a compile to link the runtime assembly the warning is generated, and then after the compile, the runtime assembly is properly linked, so the warning goes away.

As I said I have not seen this since reporting it (probably before I compiled 😁), so it's a non-issue for me.  Feel free to close this issue if you cannot find a way to reproduce it.

**Comment by Mike-EEE** [comment] 2018-10-03 11:00
Ah FWIW this did occur again after I installed 0.1.1.10 but only after I cleaned the solution and restarted Visual Studio.  However, after a little bit of time passes, the warnings do go away without the need to compile.  So it seems it is using the reference assemblies first and then ultimately finds its way to the correct assemblies.  Pretty cool for not having to compile at all. :)

**Comment by SergeyTeplyakov** [comment] 2018-10-04 05:03
Hm... I'll keep this issue opened. Maybe I'll figure out how to debug/repro this issue locally and will try to fix it.

**Comment by Mike-EEE** [comment] 2018-10-04 05:12
Cool!  I wouldn't spend TOO much time on it, as IMO this is more a nit than an actual problem like #57. 😁 😇

The new project system has introduced all sorts of weird/wonky/irritating experiences such as this with `dotnet restore` and such where messages/warnings will appear and then get removed, so worst case this fits in nicely with all the new contemporary, elegant blather. 😂

**Comment by Mike-EEE** [comment] 2018-10-18 15:47
I have an additional observation on this issue, and I am beginning to think it is not possible to solve, as I am getting this warning on my own `readonly struct` that I have created in my own .NET Standard 2.0 library.

Upon thinking about this some more, .NET Standard 2.0 doesn't have the notion/concept of `readonly struct` as it was introduced in C# 7.2.  So it would seem that the warnings are generated from .NET Standard 2.0's view of the reference/symbol files, which do not include this feature.

I am not sure if this is possible to solve, but I am OK with closing this issue until .NET Standard 2.1 is released FWIW.

**Comment by ProgrammerAl** [comment] 2020-03-18 00:35
Since this issue is still open I'll add some notes to what I just saw in case it helps others. Installed Visual Studio 16.5 (which installed .NET Core SDK 3.1.200) and after restarting my machine I started seeing these same issues. The only way I could fix this was to add a global.json file to the top level folder to force using 3.1.102 SDK when building.

**Closed** 2020-05-14 06:28 UTC
