### ISSUE TITLE
EPS06 Span false positive?

### ISSUE THREAD

**Issue by ADIX7** [SergeyTeplyakov/ErrorProne.NET#208] opened 2020-11-17 18:22 UTC
Hi,

On this sample code on line `var first = testContainer.Data[0];` EPS06 reports `Expression 'testContainer.Data' causes a hidden copy of a non-readonly struct 'Span'`.

```csharp
using System;

public readonly struct TestData
{
    public readonly int X;

    public TestData(int x)
    {
        X = x;
    }
}

public readonly ref struct TestStruct
{
    public readonly Span<TestData> Data;

    public TestStruct(Span<TestData> data)
    {
        Data = data;
    }
}

static class Program
{
    static void Main(string[] args)
    {
        Span<TestData> data = stackalloc TestData[10000];
        var testContainer = new TestStruct(data);

        var first = testContainer.Data[0];

        var data2 = testContainer.Data;
        var first2 = data2[0];
        
        Console.WriteLine();
    }
}
```

Is it false positive? Span<> (and ReadOnlySpan<>) are readonly ref structs.

On the other hand, in the second block (data2 and first2) there is no report. If the first one is positive does copy happen on line `var data2 = testContainer.Data;` without report?

**Comment by Codeusa** [comment] 2020-11-22 08:17
I can confirm I am seeing this as well.

**Comment by Djoums** [comment] 2021-09-09 07:42
This seems to be fixed with the last version.

**Comment by SergeyTeplyakov** [comment] 2021-09-09 16:21
A bunch of stuff related to struct analyzers was fixed in the past year. Closing.

**Closed by SergeyTeplyakov** 2021-09-09 16:21 UTC
